import { vi } from 'vitest';
import type { KanbanApiClient } from '../../api.js';

export function createMockClient() {
  return {
    listMissions: vi.fn(),
    getMission: vi.fn(),
    getMissionDetails: vi.fn(),
    createMission: vi.fn(),
    deleteMission: vi.fn(),
    listTasksInMission: vi.fn(),
    createTaskInMission: vi.fn(),
    getMissionContext: vi.fn(),
    getMissionProgress: vi.fn(),
    claimTask: vi.fn(),
    startTask: vi.fn(),
    updateTaskStatus: vi.fn(),
    failTask: vi.fn(),
    submitTask: vi.fn(),
    completeTask: vi.fn(),
    getTaskContext: vi.fn(),
    releaseTask: vi.fn(),
    heartbeat: vi.fn(),
    getAgent: vi.fn(),
    getAgentById: vi.fn(),
    getTask: vi.fn(),
    getHabitat: vi.fn(),
    listHabitats: vi.fn(),
    updateTask: vi.fn(),
    deleteTask: vi.fn(),
    getTaskComments: vi.fn(),
    addComment: vi.fn(),
    listSubtasks: vi.fn(),
    createSubtask: vi.fn(),
    updateSubtask: vi.fn(),
    deleteSubtask: vi.fn(),
    listAgents: vi.fn(),
    sendMessage: vi.fn(),
    getMessages: vi.fn(),
    listWebhooks: vi.fn(),
    createWebhook: vi.fn(),
    deleteWebhook: vi.fn(),
    listTemplates: vi.fn(),
    createTemplate: vi.fn(),
    deleteTemplate: vi.fn(),
    getHabitatSettings: vi.fn(),
    updateHabitatSettings: vi.fn(),
    getAgentStats: vi.fn(),
    getWorktree: vi.fn(),
    getBaseUrl: vi.fn().mockReturnValue('http://localhost:3000'),
    retryTask: vi.fn(),
    batchAssignTasks: vi.fn(),
    batchSetTaskPriority: vi.fn(),
  } as unknown as KanbanApiClient;
}
