import { vi } from "vitest";
import type { KanbanApiClient } from "../../api.js";

export function createMockClient() {
  return {
    listMissions: vi.fn(),
    getMission: vi.fn(),
    getMissionDetails: vi.fn(),
    createMission: vi.fn(),
    deleteMission: vi.fn(),
    archiveMission: vi.fn(),
    unarchiveMission: vi.fn(),
    getMissionContext: vi.fn(),
    getMissionProgress: vi.fn(),

    listTasksInMission: vi.fn(),
    createTaskInMission: vi.fn(),
    publishTaskInMission: vi.fn(),
    getClonePreparation: vi.fn(),
    publishTaskClone: vi.fn(),
    claimTask: vi.fn(),
    startTask: vi.fn(),
    updateTaskStatus: vi.fn(),
    failTask: vi.fn(),
    submitTask: vi.fn(),
    completeTask: vi.fn(),
    approveTask: vi.fn(),
    rejectTask: vi.fn(),
    getTaskContext: vi.fn(),
    releaseTask: vi.fn(),
    retryTask: vi.fn(),
    getTask: vi.fn(),
    getTaskEvents: vi.fn(),
    updateTask: vi.fn(),
    deleteTask: vi.fn(),
    delegateTask: vi.fn(),
    cloneTask: vi.fn(),
    batchAssignTasks: vi.fn(),
    batchSetTaskPriority: vi.fn(),
    batchDeleteTasks: vi.fn(),

    getHabitat: vi.fn(),
    listHabitats: vi.fn(),
    createHabitat: vi.fn(),
    getHabitatSettings: vi.fn(),
    updateHabitatSettings: vi.fn(),
    getHabitatRepository: vi.fn(),
    setHabitatRepository: vi.fn(),
    inferRepositoryFromWorktree: vi.fn(),
    inferRepositoryFromIntegration: vi.fn(),
    getPrioritizationRules: vi.fn(),
    updatePrioritizationRules: vi.fn(),
    evaluatePrioritizationRules: vi.fn(),

    postPulse: vi.fn(),
    getPulses: vi.fn(),
    getPulseDigest: vi.fn(),
    getPulseInbox: vi.fn(),
    deletePulse: vi.fn(),
    getPulseReplies: vi.fn(),
    postHabitatPulse: vi.fn(),
    getHabitatPulses: vi.fn(),
    getHabitatPulseDigest: vi.fn(),
    reactToPulse: vi.fn(),

    getTaskCodeEvidence: vi.fn(),
    linkTaskCodeEvidence: vi.fn(),
    correctTaskEvidenceLink: vi.fn(),
    markTaskEvidenceNotApplicable: vi.fn(),
    clearTaskEvidenceNotApplicable: vi.fn(),
    reportTaskEvidenceGap: vi.fn(),
    resolveTaskEvidenceGap: vi.fn(),
    getMissionCodeEvidence: vi.fn(),
    linkMissionCodeEvidence: vi.fn(),
    correctMissionEvidenceLink: vi.fn(),
    markMissionEvidenceNotApplicable: vi.fn(),
    clearMissionEvidenceNotApplicable: vi.fn(),
    reportMissionEvidenceGap: vi.fn(),
    resolveMissionEvidenceGap: vi.fn(),

    getHabitatSkill: vi.fn(),
    refreshHabitatSkill: vi.fn(),
    contributeHabitatSkill: vi.fn(),
    listSkillSignals: vi.fn(),

    heartbeat: vi.fn(),
    getAgent: vi.fn(),
    getAgentById: vi.fn(),
    listAgents: vi.fn(),
    registerAgent: vi.fn(),
    getAgentStats: vi.fn(),
    getSuggestions: vi.fn(),

    listSprints: vi.fn(),
    getActiveSprint: vi.fn(),
    getSprint: vi.fn(),
    createSprint: vi.fn(),
    updateSprint: vi.fn(),
    deleteSprint: vi.fn(),
    startSprint: vi.fn(),
    completeSprint: vi.fn(),
    cancelSprint: vi.fn(),
    addMissionToSprint: vi.fn(),
    removeMissionFromSprint: vi.fn(),

    listScheduledTasks: vi.fn(),
    createScheduledTask: vi.fn(),
    getScheduledTask: vi.fn(),
    updateScheduledTask: vi.fn(),
    deleteScheduledTask: vi.fn(),
    runScheduledTask: vi.fn(),
    enableScheduledTask: vi.fn(),
    disableScheduledTask: vi.fn(),

    listReviewRules: vi.fn(),
    createReviewRule: vi.fn(),
    updateReviewRule: vi.fn(),
    deleteReviewRule: vi.fn(),
    listTaskReviewers: vi.fn(),
    addTaskReviewer: vi.fn(),
    removeTaskReviewer: vi.fn(),

    logEffort: vi.fn(),
    listEffortEntries: vi.fn(),
    getEffortReport: vi.fn(),
    correctEffortEntry: vi.fn(),
    getMissionEffortReport: vi.fn(),

    sendMessage: vi.fn(),
    getMessages: vi.fn(),
    markMessageRead: vi.fn(),
    markAllMessagesRead: vi.fn(),
    deleteMessage: vi.fn(),

    getTaskComments: vi.fn(),
    addComment: vi.fn(),
    getMissionComments: vi.fn(),
    addMissionComment: vi.fn(),

    exportAuditLog: vi.fn(),
    getAuditSummary: vi.fn(),
    getTaskAuditBundle: vi.fn(),
    getMissionAuditBundle: vi.fn(),

    promoteInsight: vi.fn(),
    getInsights: vi.fn(),
    deactivateInsight: vi.fn(),
    getRelevantInsights: vi.fn(),

    getTaskQualityChecklist: vi.fn(),
    updateQualityChecklistItem: vi.fn(),
    validateQualityGates: vi.fn(),
    getTaskApprovalStatus: vi.fn(),

    addTaskDependency: vi.fn(),
    removeTaskDependency: vi.fn(),
    getTaskDependencies: vi.fn(),
    getTaskBlockedStatus: vi.fn(),

    getHabitatHealth: vi.fn(),
    getHabitatHealthHistory: vi.fn(),

    getHabitatSummary: vi.fn(),
    getHabitatMetrics: vi.fn(),

    listWebhooks: vi.fn(),
    createWebhook: vi.fn(),
    deleteWebhook: vi.fn(),

    listTemplates: vi.fn(),
    createTemplate: vi.fn(),
    deleteTemplate: vi.fn(),

    getTaskTimeReport: vi.fn(),

    listSubtasks: vi.fn(),
    createSubtask: vi.fn(),
    updateSubtask: vi.fn(),
    deleteSubtask: vi.fn(),
    getWorktree: vi.fn(),

    getTaskFailureContext: vi.fn(),
    getTaskWorkflowContext: vi.fn(),

    listWikiPages: vi.fn(),
    getWikiPage: vi.fn(),
    createWikiPage: vi.fn(),
    updateWikiPageMetadata: vi.fn(),
    deleteWikiPage: vi.fn(),
    listWikiVersions: vi.fn(),
    getWikiVersion: vi.fn(),
    saveWikiVersion: vi.fn(),
    restoreWikiVersion: vi.fn(),
    listWikiLinks: vi.fn(),
    addWikiPageLink: vi.fn(),
    removeWikiPageLink: vi.fn(),
    searchWiki: vi.fn(),
    markNoUpdateNeeded: vi.fn(),
    getAuthoringContextForEdit: vi.fn(),
    getAuthoringContextForChunk: vi.fn(),
    triggerWikiRefresh: vi.fn(),

    getBaseUrl: vi.fn().mockReturnValue("http://localhost:3000"),
    withAuditToolContext: vi.fn(),
  } as unknown as KanbanApiClient;
}
