import { vi } from 'vitest';
import type { KanbanApiClient } from '../../api.js';

export function createMockClient() {
  return {
    listFeatures: vi.fn(),
    getFeature: vi.fn(),
    getFeatureDetails: vi.fn(),
    createFeature: vi.fn(),
    deleteFeature: vi.fn(),
    listTasksInFeature: vi.fn(),
    createTaskInFeature: vi.fn(),
    getFeatureContext: vi.fn(),
    getFeatureProgress: vi.fn(),
    claimTask: vi.fn(),
    startTask: vi.fn(),
    updateTaskStatus: vi.fn(),
    failTask: vi.fn(),
    submitTask: vi.fn(),
    completeTask: vi.fn(),
    getTaskContext: vi.fn(),
    releaseTask: vi.fn(),
    heartbeat: vi.fn(),
    getAgent: vi.fn(),
    getAgentById: vi.fn(),
    getTask: vi.fn(),
    getBoard: vi.fn(),
    listBoards: vi.fn(),
    updateTask: vi.fn(),
    deleteTask: vi.fn(),
    getTaskComments: vi.fn(),
    addComment: vi.fn(),
    listSubtasks: vi.fn(),
    createSubtask: vi.fn(),
    updateSubtask: vi.fn(),
    deleteSubtask: vi.fn(),
    listAgents: vi.fn(),
    sendMessage: vi.fn(),
    getMessages: vi.fn(),
    listWebhooks: vi.fn(),
    createWebhook: vi.fn(),
    deleteWebhook: vi.fn(),
    listTemplates: vi.fn(),
    createTemplate: vi.fn(),
    deleteTemplate: vi.fn(),
    getBoardSettings: vi.fn(),
    updateBoardSettings: vi.fn(),
    getAgentStats: vi.fn(),
    getWorktree: vi.fn(),
    getBaseUrl: vi.fn().mockReturnValue('http://localhost:3000'),
    retryTask: vi.fn(),
    batchAssignTasks: vi.fn(),
    batchSetTaskPriority: vi.fn(),
  } as unknown as KanbanApiClient;
}
