import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
import { habitats } from './board.js';
import { missions } from './board.js';

export const integrationConnections = sqliteTable('integration_connections', {
  id: text('id').primaryKey(),
  habitatId: text('habitat_id').notNull().references(() => habitats.id, { onDelete: 'cascade' }),
  provider: text('provider', { enum: ['github', 'jira', 'linear'] }).notNull(),
  name: text('name').notNull(),
  authMethod: text('auth_method', { enum: ['oauth_device', 'oauth_code', 'oauth_pkce', 'gh_cli', 'pat', 'api_key'] }).notNull(),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  tokenExpiresAt: text('token_expires_at'),
  externalAccountId: text('external_account_id'),
  externalAccountName: text('external_account_name'),
  externalTenantId: text('external_tenant_id'),
  externalTenantName: text('external_tenant_name'),
  externalBaseUrl: text('external_base_url'),
  repositoryOwner: text('repository_owner'),
  repositoryName: text('repository_name'),
  projectKey: text('project_key'),
  teamId: text('team_id'),
  providerConfig: text('provider_config', { mode: 'json' }).$type<Record<string, unknown>>().notNull().$defaultFn(() => ({})),
  enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true),
  pullEnabled: integer('pull_enabled', { mode: 'boolean' }).notNull().default(true),
  autoImport: integer('auto_import', { mode: 'boolean' }).notNull().default(false),
  webhookSecret: text('webhook_secret'),
  webhookExternalId: text('webhook_external_id'),
  lastSyncAt: text('last_sync_at'),
  lastSyncStatus: text('last_sync_status', { enum: ['never', 'running', 'success', 'partial', 'failed'] }).notNull().default('never'),
  lastSyncError: text('last_sync_error'),
  createdBy: text('created_by').notNull(),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
  updatedAt: text('updated_at').notNull().default(sql`(datetime('now'))`),
}, (table) => [
  index('idx_integration_connections_habitat').on(table.habitatId),
  index('idx_integration_connections_provider').on(table.provider),
  index('idx_integration_connections_enabled').on(table.enabled),
]);

export const externalIntakeCandidates = sqliteTable('external_intake_candidates', {
  id: text('id').primaryKey(),
  connectionId: text('connection_id').notNull().references(() => integrationConnections.id, { onDelete: 'cascade' }),
  habitatId: text('habitat_id').notNull().references(() => habitats.id, { onDelete: 'cascade' }),
  provider: text('provider', { enum: ['github', 'jira', 'linear'] }).notNull(),
  externalId: text('external_id').notNull(),
  externalKey: text('external_key').notNull(),
  externalUrl: text('external_url').notNull(),
  sourceKind: text('source_kind'),
  sourceStatus: text('source_status'),
  sourcePriority: text('source_priority'),
  sourceAssignees: text('source_assignees', { mode: 'json' }).$type<string[]>().notNull().$defaultFn(() => []),
  sourceReporter: text('source_reporter'),
  sourceLabels: text('source_labels', { mode: 'json' }).$type<string[]>().notNull().$defaultFn(() => []),
  sourceTitle: text('source_title').notNull(),
  sourceBody: text('source_body'),
  normalizedSummary: text('normalized_summary'),
  recommendedMissionTitle: text('recommended_mission_title'),
  recommendedMissionDescription: text('recommended_mission_description'),
  reviewStatus: text('review_status', { enum: ['new', 'needs_clarification', 'ready', 'promoted', 'ignored'] }).notNull().default('new'),
  promotedMissionId: text('promoted_mission_id').references(() => missions.id, { onDelete: 'set null' }),
  rawProviderPayload: text('raw_provider_payload', { mode: 'json' }).$type<Record<string, unknown> | null>(),
  externalUpdatedAt: text('external_updated_at'),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
  updatedAt: text('updated_at').notNull().default(sql`(datetime('now'))`),
}, (table) => [
  index('idx_external_intake_candidates_connection').on(table.connectionId),
  index('idx_external_intake_candidates_habitat').on(table.habitatId),
  index('idx_external_intake_candidates_review_status').on(table.reviewStatus),
  uniqueIndex('idx_external_intake_candidates_connection_external').on(table.connectionId, table.externalId),
]);

export const externalIssueLinks = sqliteTable('external_issue_links', {
  id: text('id').primaryKey(),
  connectionId: text('connection_id').notNull().references(() => integrationConnections.id, { onDelete: 'cascade' }),
  habitatId: text('habitat_id').notNull().references(() => habitats.id, { onDelete: 'cascade' }),
  missionId: text('mission_id').notNull().references(() => missions.id, { onDelete: 'cascade' }),
  provider: text('provider', { enum: ['github', 'jira', 'linear'] }).notNull(),
  externalId: text('external_id').notNull(),
  externalKey: text('external_key').notNull(),
  externalUrl: text('external_url').notNull(),
  externalStatus: text('external_status', { enum: ['open', 'closed'] }).notNull(),
  externalUpdatedAt: text('external_updated_at'),
  providerLabels: text('provider_labels', { mode: 'json' }).$type<string[]>().notNull().$defaultFn(() => []),
  lastSyncedAt: text('last_synced_at'),
  syncStatus: text('sync_status', { enum: ['synced', 'warning', 'failed'] }).notNull().default('synced'),
  syncWarning: text('sync_warning'),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
  updatedAt: text('updated_at').notNull().default(sql`(datetime('now'))`),
}, (table) => [
  index('idx_external_issue_links_connection').on(table.connectionId),
  index('idx_external_issue_links_habitat').on(table.habitatId),
  index('idx_external_issue_links_mission').on(table.missionId),
  uniqueIndex('idx_external_issue_links_provider_external').on(table.provider, table.externalId),
  uniqueIndex('idx_external_issue_links_connection_external').on(table.connectionId, table.externalId),
]);

export const integrationSyncRuns = sqliteTable('integration_sync_runs', {
  id: text('id').primaryKey(),
  connectionId: text('connection_id').notNull().references(() => integrationConnections.id, { onDelete: 'cascade' }),
  habitatId: text('habitat_id').notNull().references(() => habitats.id, { onDelete: 'cascade' }),
  trigger: text('trigger', { enum: ['manual', 'webhook', 'scheduled', 'oauth_complete'] }).notNull(),
  status: text('status', { enum: ['running', 'success', 'partial', 'failed'] }).notNull(),
  startedAt: text('started_at').notNull(),
  finishedAt: text('finished_at'),
  createdCount: integer('created_count').notNull().default(0),
  updatedCount: integer('updated_count').notNull().default(0),
  skippedCount: integer('skipped_count').notNull().default(0),
  failedCount: integer('failed_count').notNull().default(0),
  error: text('error'),
}, (table) => [
  index('idx_integration_sync_runs_connection').on(table.connectionId),
  index('idx_integration_sync_runs_habitat').on(table.habitatId),
  index('idx_integration_sync_runs_started').on(table.startedAt),
]);
