/**
 * T11 Phase 1B — flag-gated scheduler routing tests.
 *
 * Verifies `executeScheduledTask`'s `isCreationPublicationEnabled` gate:
 *   - Flag ON → routes through the occurrence-based publication kernel
 *     (reserve → publish by shape). The three schedule shapes route to their
 *     dedicated adapters; outcomes map to the legacy `{success, missionId?,
 *     error?, skipped?}` return shape + emit the legacy SSE events.
 *   - Flag OFF → legacy `claimExecution` + `applyTemplate` /
 *     `createMissionFromSchedule` / handler-key path runs byte-unchanged
 *     (verified by the existing `scheduledTaskService.test.ts` suite, which
 *     does not set the flag — these tests don't disturb it).
 *
 * The flag-off legacy parity is covered EXHAUSTIVELY by the existing
 * `scheduledTaskService.test.ts` suite (unchanged — the flag defaults OFF
 * when these tests don't set it). This suite covers the flag-ON routing +
 * outcome-mapping that the Phase 1B change adds.
 *
 * Reference: the precedent (automationExecutor's `executeCreateTask` gate
 * at automationExecutor.ts:273-275) is covered by `automationTaskPublication.test.ts`.
 */
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { sql } from "drizzle-orm";
import { closeDb, getDb, initTestDb } from "../db/index.js";
import {
  missions,
  tasks,
  taskEvents,
  taskCreationAttempts,
  taskCreationEnvelopes,
  scheduledOccurrences,
  scheduledTasks,
  missionTemplates,
  columns as columnsTable,
  habitats,
} from "../db/schema/index.js";
import * as habitatRepo from "../repositories/habitat.js";
import * as columnRepo from "../repositories/column.js";
import * as scheduledTaskRepo from "../repositories/scheduledTask.js";
import * as templateRepo from "../repositories/template.js";
import * as scheduledTaskService from "../services/scheduledTaskService.js";
import { TASK_CREATION_INTEGRITY_VERSION } from "../db/schema/taskPublication.js";
import type { TaskPriority, TaskTemplateEntry } from "@orcy/shared";

const CUTOVER_FLAG = "ORCY_CREATION_PUBLICATION_ENABLED";
let habitatId: string;
let originalFlag: string | undefined;

beforeEach(async () => {
  await initTestDb();
  originalFlag = process.env[CUTOVER_FLAG];
  // Default: cutover flag ON — most tests exercise the migrated path.
  process.env[CUTOVER_FLAG] = "true";
  const db = getDb();
  // Wipe the seeded globals so the test habitat is a clean slate.
  db.delete(scheduledOccurrences).run();
  db.delete(scheduledTasks).run();
  db.delete(taskCreationEnvelopes).run();
  db.delete(taskCreationAttempts).run();
  db.delete(taskEvents).run();
  db.delete(tasks).run();
  db.delete(missions).run();
  db.delete(missionTemplates).run();
  db.delete(columnsTable).run();
  db.delete(habitats).run();

  const habitat = habitatRepo.createHabitat({ name: "T11 Phase 1B Habitat" });
  habitatId = habitat.id;
  columnRepo.createColumn({
    habitatId,
    name: "Backlog",
    order: 0,
    requiresClaim: false,
  });
});

afterEach(() => {
  if (originalFlag !== undefined) {
    process.env[CUTOVER_FLAG] = originalFlag;
  } else {
    delete process.env[CUTOVER_FLAG];
  }
  closeDb();
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function createSchedule(overrides: Partial<scheduledTaskRepo.CreateScheduledTaskInput> = {}): {
  id: string;
} {
  const schedule = scheduledTaskRepo.createScheduledTask({
    habitatId,
    name: "T11 Phase 1B Schedule",
    scheduleType: "interval",
    intervalMinutes: 60,
    missionTitle: "T11 Phase 1B Mission",
    missionDescription: "Auto-generated by the scheduler.",
    missionPriority: "medium" as TaskPriority,
    missionLabels: ["t11"],
    tasksTemplate: [],
    nextRunAt: new Date().toISOString(),
    createdBy: "test",
    ...overrides,
  });
  return { id: schedule.id };
}

/** Count helper for routing assertions. */
function countRows() {
  const db = getDb();
  return {
    missions: db
      .select({ count: sql<number>`COUNT(*)` })
      .from(missions)
      .get()!.count,
    tasks: db
      .select({ count: sql<number>`COUNT(*)` })
      .from(tasks)
      .get()!.count,
    occurrences: db
      .select({ count: sql<number>`COUNT(*)` })
      .from(scheduledOccurrences)
      .get()!.count,
    envelopes: db
      .select({ count: sql<number>`COUNT(*)` })
      .from(taskCreationEnvelopes)
      .get()!.count,
  };
}

/** Reads the single occurrence row (throws if not exactly one). */
function readOccurrence() {
  const rows = getDb().select().from(scheduledOccurrences).all();
  if (rows.length !== 1) {
    throw new Error(`expected exactly 1 occurrence row, found ${rows.length}`);
  }
  return rows[0];
}

// ---------------------------------------------------------------------------
// Routing — flag ON routes each shape to its dedicated publication adapter
// ---------------------------------------------------------------------------

describe("T11 Phase 1B — flag-gated scheduler routing", () => {
  describe("flag ON + templateId set → publishScheduledOccurrence", () => {
    it("reserves the occurrence, publishes via the templateId path, links the Mission + creates POST_CUTOVER Tasks", () => {
      const template = templateRepo.createTemplate({
        habitatId,
        name: "Template Routing Test",
        titlePattern: "Templated Task",
        descriptionPattern: "## Goal\nComplete the work",
        priority: "medium" as TaskPriority,
        labels: ["t11"],
        requiredDomain: "backend",
        requiredCapabilities: ["typescript"],
        tasksTemplate: [
          { title: "First", order: 0 },
          { title: "Second", order: 1 },
        ] as TaskTemplateEntry[],
        createdBy: "test",
      });
      const schedule = createSchedule({
        templateId: template.id,
        // The templateId path keys Tasks off the template; the schedule's
        // own tasksTemplate stays empty so the inline path is NOT eligible.
        tasksTemplate: [],
      });

      const result = scheduledTaskService.executeScheduledTask(schedule.id);

      expect(result.success).toBe(true);
      expect(result.missionId).toBeTruthy();

      // The occurrence record is created + transitions to `published`.
      const occurrence = readOccurrence();
      expect(occurrence.state).toBe("published");
      expect(occurrence.createdMissionId).toBe(result.missionId);
      expect(occurrence.scheduledTaskId).toBe(schedule.id);

      // Tasks are POST_CUTOVER (the new kernel stamps creationIntegrity=1;
      // the legacy path leaves it at the default 0).
      const taskRows = getDb().select().from(tasks).all();
      expect(taskRows).toHaveLength(2);
      for (const t of taskRows) {
        expect(t.creationIntegrity).toBe(TASK_CREATION_INTEGRITY_VERSION.POST_CUTOVER);
      }

      // The schedule advanced exactly once (reservation owns the advance).
      const scheduleAfter = scheduledTaskRepo.getScheduledTaskById(schedule.id);
      expect(scheduleAfter!.runCount).toBe(1);
      expect(scheduleAfter!.lastCreatedMissionId).toBe(result.missionId);
      // nextRunAt advanced beyond the original (interval = +60m).
      expect(new Date(scheduleAfter!.nextRunAt).getTime()).toBeGreaterThan(Date.now() - 1000);
    });

    it("emits the scheduled_task.executed SSE event on success (UI parity)", () => {
      // SSE is a side effect; we verify it indirectly via the absence of
      // throws + the success return. The broadcaster is not mocked here —
      // it writes to an in-memory channel. The success return + occurrence
      // `published` state is the authoritative signal.
      const template = templateRepo.createTemplate({
        habitatId,
        name: "SSE Template",
        titlePattern: "SSE Task",
        priority: "medium" as TaskPriority,
        labels: [],
        tasksTemplate: [{ title: "T", order: 0 }] as TaskTemplateEntry[],
        createdBy: "test",
      });
      const schedule = createSchedule({ templateId: template.id, tasksTemplate: [] });

      const result = scheduledTaskService.executeScheduledTask(schedule.id);

      expect(result.success).toBe(true);
      expect(result.missionId).toBeTruthy();
    });
  });

  describe("flag ON + tasksTemplate non-empty (no templateId) → publishInlineScheduledOccurrence", () => {
    it("reserves the occurrence, publishes via the inline path, creates a Mission + POST_CUTOVER Tasks", () => {
      const schedule = createSchedule({
        tasksTemplate: [
          { title: "Inline Task A", description: "desc", order: 0 },
          { title: "Inline Task B", description: "desc", order: 1 },
        ] as TaskTemplateEntry[],
      });

      const result = scheduledTaskService.executeScheduledTask(schedule.id);

      expect(result.success).toBe(true);
      expect(result.missionId).toBeTruthy();

      const occurrence = readOccurrence();
      expect(occurrence.state).toBe("published");
      expect(occurrence.createdMissionId).toBe(result.missionId);

      const taskRows = getDb().select().from(tasks).all();
      expect(taskRows).toHaveLength(2);
      for (const t of taskRows) {
        expect(t.creationIntegrity).toBe(TASK_CREATION_INTEGRITY_VERSION.POST_CUTOVER);
      }

      const scheduleAfter = scheduledTaskRepo.getScheduledTaskById(schedule.id);
      expect(scheduleAfter!.runCount).toBe(1);
    });
  });

  describe("flag ON + handlerKey set → dispatchHandlerScheduledOccurrence", () => {
    it("reserves the occurrence, dispatches via the handler path, no Mission linked (createdMissionId null)", () => {
      // Register a handler for the test. The handler key must be unique
      // enough not to collide with production registrars.
      const handlerKey = "t11-phase1b-test-handler";
      scheduledTaskService.registerScheduledTaskHandler(handlerKey, () => ({
        success: true,
      }));

      const schedule = createSchedule({
        handlerKey,
        tasksTemplate: [],
      });

      const result = scheduledTaskService.executeScheduledTask(schedule.id);

      expect(result.success).toBe(true);
      // Handler dispatch produces no Mission; the return omits missionId.
      expect(result.missionId).toBeUndefined();

      const occurrence = readOccurrence();
      expect(occurrence.state).toBe("published");
      // The handler dispatch path stamps createdMissionId = null (handlers
      // produce no Mission at the occurrence level).
      expect(occurrence.createdMissionId).toBeNull();

      // No Tasks created (handler returned success without spawning Tasks).
      expect(countRows().tasks).toBe(0);

      const scheduleAfter = scheduledTaskRepo.getScheduledTaskById(schedule.id);
      expect(scheduleAfter!.runCount).toBe(1);
    });

    it("surfaces the handler's optional missionId on success for legacy parity", () => {
      const handlerKey = "t11-phase1b-handler-with-mission";
      const handlerMissionId = "handler-spawned-mission-id";
      scheduledTaskService.registerScheduledTaskHandler(handlerKey, () => ({
        success: true,
        missionId: handlerMissionId,
      }));

      const schedule = createSchedule({ handlerKey, tasksTemplate: [] });

      const result = scheduledTaskService.executeScheduledTask(schedule.id);

      expect(result.success).toBe(true);
      // The handler's missionId is surfaced on the return (legacy parity —
      // the legacy handler branch returns the handlerResult.missionId).
      expect(result.missionId).toBe(handlerMissionId);
    });

    it("returns failure when no handler is registered for the handlerKey", () => {
      const schedule = createSchedule({
        handlerKey: "t11-phase1b-unregistered-handler",
        tasksTemplate: [],
      });

      const result = scheduledTaskService.executeScheduledTask(schedule.id);

      expect(result.success).toBe(false);
      expect(result.error).toMatch(/No handler registered/);

      // The occurrence terminally rejects (handler_not_registered).
      const occurrence = readOccurrence();
      expect(occurrence.state).toBe("rejected");
    });
  });

  // -----------------------------------------------------------------------
  // Routing precedence — preserves the legacy handlerKey > templateId > inline
  // -----------------------------------------------------------------------

  describe("routing precedence (preserves legacy handlerKey > templateId > inline)", () => {
    it("routes to the handler path when BOTH handlerKey + templateId are set", () => {
      const handlerKey = "t11-phase1b-precedence-handler";
      scheduledTaskService.registerScheduledTaskHandler(handlerKey, () => ({
        success: true,
      }));

      const template = templateRepo.createTemplate({
        habitatId,
        name: "Precedence Template",
        titlePattern: "Should NOT be used",
        priority: "medium" as TaskPriority,
        labels: [],
        tasksTemplate: [{ title: "Should NOT appear", order: 0 }] as TaskTemplateEntry[],
        createdBy: "test",
      });

      const schedule = createSchedule({
        handlerKey,
        templateId: template.id,
        tasksTemplate: [],
      });

      const result = scheduledTaskService.executeScheduledTask(schedule.id);

      expect(result.success).toBe(true);
      // Handler path: no missionId on the return + no Tasks created.
      expect(result.missionId).toBeUndefined();
      expect(countRows().tasks).toBe(0);

      const occurrence = readOccurrence();
      expect(occurrence.state).toBe("published");
      expect(occurrence.createdMissionId).toBeNull();
    });
  });

  // -----------------------------------------------------------------------
  // Outcome mapping — publication outcomes → legacy return shape
  // -----------------------------------------------------------------------

  describe("outcome mapping — reservation rejected (schedule not due)", () => {
    it("returns failure when the reservation rejects (schedule_not_due)", () => {
      // A schedule whose nextRunAt is in the future. The legacy path's
      // `claimExecution` would advance it anyway (it doesn't check due-ness
      // — the due-check is in `getDueScheduledTasks`). The new path's
      // reservation rejects with `schedule_not_due` (the in-tx due CAS).
      const schedule = createSchedule({
        nextRunAt: new Date(Date.now() + 3600_000).toISOString(),
      });

      const result = scheduledTaskService.executeScheduledTask(schedule.id);

      expect(result.success).toBe(false);
      expect(result.error).toMatch(/reservation rejected/);
      // No occurrence row persists (the reservation tx rolled back).
      expect(countRows().occurrences).toBe(0);
      // Schedule did not advance.
      const scheduleAfter = scheduledTaskRepo.getScheduledTaskById(schedule.id);
      expect(scheduleAfter!.runCount).toBe(0);
    });
  });

  // -----------------------------------------------------------------------
  // nextRunAt advancement — the load-bearing correctness invariant
  // -----------------------------------------------------------------------

  describe("nextRunAt advancement (no double-advance)", () => {
    it("advances the schedule exactly once via the reservation (NOT claimExecution)", () => {
      const schedule = createSchedule({
        tasksTemplate: [{ title: "T", order: 0 }] as TaskTemplateEntry[],
      });
      const before = scheduledTaskRepo.getScheduledTaskById(schedule.id);
      expect(before!.runCount).toBe(0);

      const result = scheduledTaskService.executeScheduledTask(schedule.id);

      expect(result.success).toBe(true);
      const after = scheduledTaskRepo.getScheduledTaskById(schedule.id);
      // Exactly ONE advance (the reservation's `advanceScheduleOnceWithClient`
      // CAS). If `claimExecution` ALSO ran, runCount would be 2.
      expect(after!.runCount).toBe(1);
      expect(after!.lastRunAt).toBeTruthy();
    });
  });

  // -----------------------------------------------------------------------
  // Flag OFF — legacy path (byte-identical, no occurrence record)
  // -----------------------------------------------------------------------

  describe("flag OFF → legacy executeScheduledTask path", () => {
    it("uses the legacy createMissionFromSchedule path (no occurrence record, Tasks are LEGACY_PARTIAL_HISTORY)", () => {
      delete process.env[CUTOVER_FLAG];

      const schedule = createSchedule({
        tasksTemplate: [{ title: "Legacy Task", order: 0 }] as TaskTemplateEntry[],
      });

      const result = scheduledTaskService.executeScheduledTask(schedule.id);

      expect(result.success).toBe(true);
      expect(result.missionId).toBeTruthy();

      // The legacy path creates NO occurrence record.
      expect(countRows().occurrences).toBe(0);

      // The legacy path leaves creationIntegrity at the default 0
      // (LEGACY_PARTIAL_HISTORY). The new path stamps 1 (POST_CUTOVER).
      const taskRows = getDb().select().from(tasks).all();
      expect(taskRows).toHaveLength(1);
      expect(taskRows[0].creationIntegrity).toBe(
        TASK_CREATION_INTEGRITY_VERSION.LEGACY_PARTIAL_HISTORY,
      );

      // Schedule advanced via `claimExecution` (exactly once).
      const after = scheduledTaskRepo.getScheduledTaskById(schedule.id);
      expect(after!.runCount).toBe(1);
    });
  });
});
