/**
 * T9A-11 — REAL cross-process concurrency for `reserveScheduledOccurrence`.
 *
 * The existing "concurrent same-key reservation" test in
 * `scheduledOccurrenceReservation.test.ts` is SEQUENTIAL replay (reserve →
 * reserve same key → `already_exists`). It does NOT exercise the real
 * UNIQUE-race or the multi-connection schedule-advance CAS — it proves only
 * the function's idempotent-replay CLASSIFICATION, not the underlying
 * SQLite-level race defense. This file closes that gap with a REAL
 * child-process race (the MEMORY.md § Migration Plumbing pattern +
 * `f4BusyTimeout.test.ts` precedent).
 *
 * Two worker processes (`fixtures/t9a11-reservation-worker.ts`) each open
 * their OWN better-sqlite3 file connection + each call
 * `reserveScheduledOccurrence` for the SAME schedule at the SAME time.
 * The assertion: exactly ONE occurrence created, the schedule advanced
 * EXACTLY once (runCount delta = 1), + the loser gets a typed outcome
 * (`already_exists` OR `lost_race`).
 *
 * # Why a child process (not two connections on one event loop)
 *
 * better-sqlite3 is synchronous — two connections on one event loop
 * serialize by construction (the event loop runs one write to completion
 * before starting the next). That would be a serial substitute, not real
 * overlapping lock ownership (the f4BusyTimeout guardrail + MEMORY.md
 * pattern). Two OS processes genuinely race for the file-level write lock.
 *
 * # Why a separate file (not appended to scheduledOccurrenceReservation.test.ts)
 *
 * The other reservation tests use `initTestDb()` (sql.js, in-memory). THIS
 * test needs a REAL better-sqlite3 FILE DB (shared between the parent +
 * the forked workers via SQLite's file-locking protocol). The
 * close/re-init dance would be fragile when sharing a file with the sql.js
 * tests — f4BusyTimeout.test.ts sets the precedent of separating file-DB
 * concurrency tests into their own file.
 *
 * exfat caveat (per the ticket): real overlapping SQLite write tests are
 * sometimes slow / flaky on exfat (disk I/O transient errors). The test
 * retries cleanly via the workers' own `busy_timeout = 5000` pragma (set
 * by `initDb`).
 */
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { fork, type ChildProcess } from "node:child_process";
import { join } from "node:path";
import { existsSync, unlinkSync, mkdirSync } from "node:fs";
import { eq } from "drizzle-orm";
import { closeDb, getDb, initDb } from "../db/index.js";
import { scheduledOccurrences, scheduledTasks } from "../db/schema/index.js";
import * as habitatRepo from "../repositories/habitat.js";
import * as scheduledTaskRepo from "../repositories/scheduledTask.js";
import type { TaskPriority } from "@orcy/shared";

const WORKER = join(import.meta.dirname, "fixtures", "t9a11-reservation-worker.ts");
const TEMP_DIR = join(import.meta.dirname, "..", "..", ".test-t9a11");

const NOW_ISO = "2026-07-19T12:00:00.000Z";
const NEXT_RUN_INTERVAL = "2026-07-19T13:00:00.000Z"; // 1h after NOW

interface WorkerMessage {
  type: "READY" | "RESULT" | "ERROR";
  outcome?: string;
  occurrenceId?: string | null;
  advanced?: boolean | null;
  message?: string;
}

function cleanupDb(dbPath: string): void {
  for (const suffix of ["", "-wal", "-shm"]) {
    if (existsSync(`${dbPath}${suffix}`)) {
      try {
        unlinkSync(`${dbPath}${suffix}`);
      } catch {
        // ignore — already gone
      }
    }
  }
}

describe("reserveScheduledOccurrence — real cross-process concurrency (T9A-11)", () => {
  let dbPath: string;

  beforeEach(() => {
    if (!existsSync(TEMP_DIR)) mkdirSync(TEMP_DIR, { recursive: true });
    dbPath = join(TEMP_DIR, `t9a11-${Date.now()}-${Math.random().toString(36).slice(2)}.db`);
    cleanupDb(dbPath);
    closeDb();
  });

  afterEach(() => {
    closeDb();
    cleanupDb(dbPath);
  });

  it("two workers racing the SAME schedule → exactly ONE occurrence + runCount advanced EXACTLY once", async () => {
    // ----- PARENT SETUP: open the file DB + seed a schedule ------------
    await initDb(dbPath);
    const db = getDb();

    const habitat = habitatRepo.createHabitat({ name: "T9A-11 Concurrency Habitat" });
    const schedule = scheduledTaskRepo.createScheduledTask({
      habitatId: habitat.id,
      name: "Raced Schedule",
      scheduleType: "interval",
      intervalMinutes: 60,
      missionTitle: "Raced mission",
      missionDescription: "Auto-generated by the concurrency test.",
      missionPriority: "medium" as TaskPriority,
      missionLabels: ["concurrency"],
      tasksTemplate: [],
      nextRunAt: NOW_ISO,
      createdBy: "test",
    });
    const scheduleId = schedule.id;

    // Sanity: pre-race state — schedule due, no occurrences.
    expect(db.select().from(scheduledOccurrences).all()).toHaveLength(0);
    expect(
      db.select().from(scheduledTasks).where(eq(scheduledTasks.id, scheduleId)).get()!.runCount,
    ).toBe(0);

    // Close the PARENT's connection before forking so the workers race
    // against a clean lock state (no parent-held WAL/handle interference).
    // Re-open post-race for the assertions.
    closeDb();

    // ----- FORK TWO WORKERS --------------------------------------------
    const forkWorker = (
      label: string,
    ): {
      child: ChildProcess;
      ready: Promise<void>;
      result: Promise<WorkerMessage>;
    } => {
      const child = fork(WORKER, [dbPath, scheduleId, NEXT_RUN_INTERVAL, NOW_ISO, NOW_ISO], {
        execArgv: ["--import", "tsx"],
        stdio: ["pipe", "pipe", "pipe", "ipc"],
      });
      // Surface worker stderr for diagnostics (zero-noise on pass; workers
      // only write to stderr on unexpected errors).
      child.stderr?.on("data", (chunk: Buffer) => {
        console.warn(`[T9A-11 worker-${label} stderr]:`, chunk.toString());
      });
      const ready = new Promise<void>((resolve, reject) => {
        const onMessage = (msg: WorkerMessage): void => {
          if (msg?.type === "READY") {
            child.off("message", onMessage);
            resolve();
          }
        };
        child.on("message", onMessage);
        child.on("exit", (code, signal) => {
          reject(new Error(`worker exited (code=${code}, signal=${signal}) before READY`));
        });
      });
      const result = new Promise<WorkerMessage>((resolve) => {
        const onMessage = (msg: WorkerMessage): void => {
          if (msg?.type === "RESULT" || msg?.type === "ERROR") {
            child.off("message", onMessage);
            resolve(msg);
          }
        };
        child.on("message", onMessage);
      });
      return { child, ready, result };
    };

    const w1 = forkWorker("1");
    const w2 = forkWorker("2");

    try {
      // Wait for both workers to be primed (DB open + module loaded).
      await Promise.all([w1.ready, w2.ready]);

      // Fire BOTH as close to simultaneously as the event loop allows.
      // The workers' deferred-call design (READY sent AFTER the function
      // module is imported; GO triggers ONLY the call) minimizes skew.
      w1.child.send({ type: "GO" });
      w2.child.send({ type: "GO" });

      // Collect both results.
      const [r1, r2] = await Promise.all([w1.result, w2.result]);

      // Surface worker errors visibly (zero-noise on pass; only fires if
      // a worker hits an infrastructure throw rather than a typed outcome).
      if (r1.type === "ERROR") console.warn("[T9A-11 worker-1 ERROR]:", r1.message);
      if (r2.type === "ERROR") console.warn("[T9A-11 worker-2 ERROR]:", r2.message);

      // Neither worker should error — the race outcomes are typed
      // (created | already_exists | lost_race), not thrown.
      expect(r1.type).toBe("RESULT");
      expect(r2.type).toBe("RESULT");

      // ----- THE LOAD-BEARING ASSERTION: one winner, one typed loser ---
      // Exactly ONE worker created the occurrence (UNIQUE index defense);
      // the other got a typed race-loser outcome (already_exists via the
      // UNIQUE-collision branch OR lost_race via the schedule-advance CAS
      // loss). The function's closed discriminated union classifies both.
      const outcomes = [r1.outcome!, r2.outcome!];
      const winners = outcomes.filter((o) => o === "created");
      const losers = outcomes.filter((o) => o === "already_exists" || o === "lost_race");
      expect(winners).toHaveLength(1);
      expect(losers).toHaveLength(1);

      // **Failure mode**: if the UNIQUE index failed to defend (both
      // INSERTed), winners would be 2. If the CAS re-advanced on the
      // already_exists branch, runCount would be 2 (asserted below).
    } finally {
      // Ensure no lingering workers regardless of assertion outcome.
      for (const w of [w1, w2]) {
        if (w.child.exitCode === null && !w.child.killed) w.child.kill("SIGKILL");
      }
    }

    // ----- PARENT POST-RACE ASSERTIONS: durable DB state ----------------
    await initDb(dbPath);
    const db2 = getDb();

    // Exactly ONE occurrence row exists for this schedule.
    const occurrenceRows = db2
      .select()
      .from(scheduledOccurrences)
      .where(eq(scheduledOccurrences.scheduledTaskId, scheduleId))
      .all();
    expect(occurrenceRows).toHaveLength(1);

    // THE LOAD-BEARING ASSERTION: the schedule advanced EXACTLY once
    // (runCount = 1), no double-counting despite two concurrent
    // reservations. The UNIQUE index (one occurrence per schedule per
    // due timestamp) + the schedule-advance CAS predicate
    // (`enabled = true AND nextRunAt <= now`) + the lost-race sentinel
    // (T9A-02: a fresh insert that loses the CAS rolls back the whole
    // tx) jointly defend this. A sequential replay cannot prove it —
    // the real cross-process race is the only faithful proof.
    const scheduleAfter = db2
      .select()
      .from(scheduledTasks)
      .where(eq(scheduledTasks.id, scheduleId))
      .get();
    expect(scheduleAfter!.runCount).toBe(1);
    expect(scheduleAfter!.nextRunAt).toBe(NEXT_RUN_INTERVAL);
    // Recurring schedule stays enabled (one-shot disablement is tested
    // separately in the main reservation suite).
    expect(scheduleAfter!.enabled).toBe(true);

    // **Failure mode**: pre-T9A-02 (arc 1), a fresh-insert CAS-loss
    // returned `{outcome:"created", advanced:false}` — persisting a
    // dangling reserved occurrence this reservation didn't claim + NOT
    // rolling back. Under real concurrency the loser would hit that
    // branch → occurrenceRows would be 2 + runCount could be 1 or 2.
    // Post-T9A-02 the loser either gets `already_exists` (UNIQUE
    // collision, no-op advance) OR `lost_race` (CAS loss, full tx
    // rollback) — never `created, advanced:false`.
  }, 30_000);
});
