-- ============================================================================
-- IMMUTABLE MIGRATION - DO NOT EDIT (F3 freeze, ADR-0039 Q9)
-- ----------------------------------------------------------------------------
-- This file is FROZEN. Its shipped content must never be edited, renamed, or
-- deleted after release. It is owned SOLELY by the Drizzle migration journal
-- restored in F2; there is no out-of-band runner and no second ledger writer.
--
-- WHY FROZEN: the sole statement below is a blanket
--   DELETE FROM plugin_quarantines
-- that cannot distinguish legacy rows from canonical kind-aware rows. Re-running
-- it would wipe live fault-state quarantines added after the one-time reset.
--
-- ONE-SHOT GUARANTEE: Drizzle's migrator selects migrations by journal `when`
-- (folderMillis) timestamp, NOT by file hash. Once `migrate()` records this
-- file's SHA-256 at `created_at = journal.when`, it never re-runs on later
-- boots. A comment-only edit to these bytes changes the hash but cannot change
-- `when`, so it cannot retrigger the destructive statement - proven by the F3
-- `comment-only mutation cannot retrigger` test.
--
-- HASH BRIDGE: a prerelease build recorded this file's hash out-of-band with
-- `created_at = Date.now()`, which suppressed the whole 0027-0053 chain.
-- `reconcilePrereleaseMigrationMarker()` in `src/db/index.ts` recognizes BOTH
-- the current file hash AND the legacy pre-F3 hash
-- (`PRERELEASE_0053_MARKER_HASH`) so that prepending this banner did not strand
-- the old high-timestamp marker. Any future change requires a NEW migration
-- with a new ordered identity, never an edit to this file.
-- ============================================================================
-- v0.28-T2 (ADR-0039 Q9): One-time prerelease plugin quarantine reset.
--
-- Existing plugin_quarantines rows use the ambiguous `${pluginId}:${contributionId}`
-- composite key, which is NOT kind-safe: the same `pluginId:contributionId`
-- string can refer to a signalDetector, automationAction, or notificationChannel
-- contribution, and Lifecycle Interceptor keys additionally need phase+event to
-- disambiguate a single interceptorId that legitimately appears in multiple
-- lifecycle positions.
--
-- The new canonical key format is a JSON-encoded tuple:
--   `["signalDetector",pluginId,contributionId]`
--   `["lifecycleInterceptor",pluginId,interceptorId,phase,event]`
-- produced by the single `canonicalContributionKey` encoder in
-- `packages/api/src/plugins/contributionAdapters.ts`. Legacy rows cannot be
-- mapped deterministically to the new format because the legacy key does not
-- encode kind/phase/event — guessing would silently re-quarantine the wrong
-- contribution. Delete them instead.
--
-- Quarantine is ephemeral fault-state: if a fault persists, the contribution
-- is re-quarantined naturally on the next error threshold crossing. This is a
-- prerelease reset and must be documented in the release notes for the release
-- that ships ADR-0039 T2.
DELETE FROM plugin_quarantines;
